create extension if not exists pgcrypto;

create table if not exists public.bug_reports (
  id uuid primary key default gen_random_uuid(),
  report_number bigint generated by default as identity unique,
  client_report_id text not null unique,
  surface text not null
    check (surface in ('reefbound', 'simulator')),
  summary text not null
    check (char_length(summary) between 4 and 160),
  description text not null
    check (char_length(description) between 10 and 4000),
  steps text not null default ''
    check (char_length(steps) <= 4000),
  expected_behavior text not null default ''
    check (char_length(expected_behavior) <= 2000),
  impact text not null default 'unsure'
    check (impact in ('blocked', 'lost-progress', 'can-continue', 'visual', 'unsure')),
  context jsonb not null default '{}'::jsonb
    check (octet_length(context::text) <= 16000),
  priority text not null default 'untriaged'
    check (priority in ('critical', 'high', 'normal', 'low', 'untriaged')),
  status text not null default 'new'
    check (status in ('new', 'investigating', 'in-progress', 'fixed', 'closed')),
  approved_for_fix boolean not null default false,
  approved_at timestamptz,
  admin_notes text not null default ''
    check (char_length(admin_notes) <= 4000),
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz
);

create index if not exists bug_reports_priority_submitted_at_idx
  on public.bug_reports (priority, submitted_at desc);

create index if not exists bug_reports_status_submitted_at_idx
  on public.bug_reports (status, submitted_at desc);

create index if not exists bug_reports_approved_for_fix_idx
  on public.bug_reports (approved_for_fix, priority, submitted_at desc)
  where approved_for_fix = true;

alter table public.bug_reports enable row level security;

drop policy if exists "Bug reports are private" on public.bug_reports;
create policy "Bug reports are private"
  on public.bug_reports
  for all
  using (false)
  with check (false);

revoke all on table public.bug_reports from anon, authenticated;
revoke all on sequence public.bug_reports_report_number_seq from anon, authenticated;
