import { ELVERSON_TOWN_WEST_COVE } from "./adventureElversonTownLayout.mjs";

export const ELVERSON_AMBIENT_RESIDENTS = Object.freeze([
  {
    id: "fisherman-wyeth",
    name: "Fisherman Wyeth",
    title: "Fisherman's Wharf Guide",
    sceneId: "town",
    at: ELVERSON_TOWN_WEST_COVE.wyeth,
    intro: "It's a fine day for fishing! I hear you'd like to learn how to catch some sea creatures? Let's start with a good old-fashioned hand net.",
    guidance: "A hand net is for the shallow shore. Move slowly, watch the animal's path, and never chase it into a place where you could damage its shelter.",
    returnLine: "Meet me at the sandy practice cove when you're ready for your first hand-net lesson.",
    fishingLesson: [
      "Mr. Easterling asked me to help you gather possible residents for the aquarium. First, we use only marked collection areas and stop whenever wildlife, weather, or footing makes the work unsafe.",
      "We'll begin with a hand net in the shallow cove. Small reef fish, crabs, and other invertebrates can be quick, so approach gently and avoid startling them.",
      "Follow me to the practice edge. Once you complete the lesson, the hand net is yours to keep.",
    ],
    fishingPractice: [
      "We still need to complete your first hand-net catch together.",
      "Follow me to the sandy practice cove. Slow and steady is the trick.",
    ],
    fishingGuidance: [
      "Your hand net is ready for marked shallow-water areas. It can collect crabs, invertebrates, and small reef fish under twelve inches long.",
      "Bring every successful catch to Mr. Easterling so the aquarium care team can check its needs and award its matching Sea Realm card.",
    ],
  },
  {
    id: "town-theo",
    name: "Theo",
    title: "Elverson Deck Builder",
    sceneId: "town",
    at: { x: 7, y: 8.35 },
    intro: "A healthy ecosystem comprises every layer of the food chain. Well-balanced SeaRealm decks reflect this in their design.",
    guidance: "Producers, small consumers, mid-level hunters, and apex predators all need support from the layers beneath them.",
    returnLine: "When a deck feels uneven, check which part of its food chain is missing.",
  },
  {
    id: "eli",
    name: "Eli",
    title: "Elverson Deck Builder",
    sceneId: "town",
    at: { x: 16.8, y: 8.35 },
    intro: "Did you know that support cards are designed to help you solve problems when playing SeaRealm?",
    guidance: "They can help you search for creatures, heal corals, and do many other useful things.",
    returnLine: "A good support card is often the answer your ecosystem needs at exactly the right time.",
  },
  {
    id: "micah",
    name: "Micah",
    title: "Elverson Deck Builder",
    sceneId: "town",
    at: { x: 24.2, y: 8.35 },
    intro: "All creatures have a habitat that they were designed for.",
    guidance: "When playing SeaRealm, many cards unlock abilities if you have the right habitat in play.",
    returnLine: "Build the habitat first, and its creatures can show you what they really do.",
  },
  {
    id: "town-erik",
    name: "Erik",
    title: "Elverson Naturalist",
    sceneId: "aquarium-reef-gallery",
    at: { x: 19, y: 6.25 },
    patrol: {
      mode: "ping-pong",
      speed: 0.52,
      pauseMs: 800,
      playerPauseDistance: 1,
      waypoints: [{ x: 19, y: 6.25 }, { x: 28, y: 6.25 }],
    },
    intro: "Invertebrates are small, but crucial to any reef ecosystem.",
    guidance: "They help recycle nutrients and serve as a vital food source for larger creatures.",
    returnLine: "Tiny animals can hold an enormous ecosystem together.",
  },
  {
    id: "henderson",
    name: "Henderson",
    title: "Elverson Supply Company Clerk",
    sceneId: "elverson-supply-company",
    at: { x: 7, y: 2.5 },
    intro: "Welcome to Elverson Supply Company! I keep practical, habitat-safe gear ready for every kind of adventure.",
    guidance: "Choose tools for the creature, habitat, and conditions you expect, and inspect every item before you leave town.",
    returnLine: "If you're unsure what to carry, tell me where you're headed and what you hope to study.",
  },
  {
    id: "sam",
    name: "Sam",
    title: "Age 8 · Aspiring Collector",
    sceneId: "elverson-supply-company",
    at: { x: 4, y: 4.5 },
    intro: "I'm looking for just the right cast net before I set out on my adventure!",
    guidance: "Henderson says the mesh and size should match the job so the net can be used responsibly.",
    returnLine: "There are so many nets to compare!",
  },
  {
    id: "ellis",
    name: "Ellis",
    title: "Age 10 · Aspiring Angler",
    sceneId: "elverson-supply-company",
    at: { x: 7, y: 4.5 },
    intro: "I just got a fishing rod! This will help me catch fish that a net can't reach.",
    guidance: "Wyeth says different tools belong in different collection areas, and every catch must be handled gently.",
    returnLine: "I can't wait to learn where a rod is safe to use.",
  },
  {
    id: "karah",
    name: "Karah",
    title: "Prepared Adventurer",
    sceneId: "elverson-supply-company",
    at: { x: 10, y: 4.5 },
    intro: "With so many creatures to collect, make sure you stock up on essential items.",
    guidance: "Water, weather protection, safe carriers, and a clear plan matter just as much as collection gear.",
    returnLine: "Preparation makes every adventure safer and more enjoyable.",
  },
  {
    id: "finn",
    name: "Finn",
    title: "SeaRealm Deck Designer",
    sceneId: "aquarium-reef-gallery",
    at: { x: 4, y: 6.25 },
    patrol: {
      mode: "ping-pong",
      speed: 0.58,
      pauseMs: 650,
      playerPauseDistance: 1,
      waypoints: [{ x: 4, y: 6.25 }, { x: 13.5, y: 6.25 }],
    },
    intro: "SeaRealm decks can be customized to your liking. I designed Murky Water's Revenge!",
    guidance: "Changing a few cards can shift a deck's plan while keeping its ecosystem foundation intact.",
    returnLine: "Once you know how your starter works, imagine the version that feels most like yours.",
  },
  {
    id: "ivy",
    name: "Ivy",
    title: "Aquarium Cataloguer",
    sceneId: "aquarium-oceanic-gallery",
    at: { x: 5, y: 6.25 },
    patrol: {
      mode: "ping-pong",
      speed: 0.55,
      pauseMs: 700,
      playerPauseDistance: 1,
      waypoints: [{ x: 5, y: 6.25 }, { x: 14, y: 6.25 }],
    },
    intro: "I'm helping Mr. Easterling catalogue all the different species we collect for the aquarium.",
    guidance: "Each record connects the creature to its habitat, care needs, exhibit room, and matching Sea Realm card.",
    returnLine: "Bring us something new and I'll make sure its record is ready.",
  },
  {
    id: "teacher-caroline",
    name: "Teacher Caroline",
    title: "Red Schoolhouse Teacher",
    sceneId: "elverson-red-schoolhouse",
    at: { x: 7, y: 2.5 },
    intro: "Hello there! Mr. Easterling told my class about the aquarium exhibit. We are writing descriptions for the various Sea Creature exhibits.",
    guidance: "A strong exhibit description is accurate, vivid, and clear enough for visitors of every age.",
    returnLine: "My students would love to share the species notes they prepared.",
  },
  {
    id: "red-schoolhouse-hudson",
    name: "Hudson",
    title: "Age 6 · Student",
    sceneId: "elverson-red-schoolhouse",
    at: { x: 3.5, y: 4.5 },
    intro: "Sea Anemones may look like swaying flowers, but they are animal cousins of corals and jellyfish.",
    guidance: "Their tentacles fire microscopic stinging capsules that capture prey and discourage hungry visitors.",
    returnLine: "I think anemones will look amazing in a reef exhibit!",
  },
  {
    id: "red-schoolhouse-harrison",
    name: "Harrison",
    title: "Age 6 · Student",
    sceneId: "elverson-red-schoolhouse",
    at: { x: 5.8, y: 5.5 },
    intro: "Arrow Crabs tiptoe over Caribbean reefs on extremely long, skinny legs.",
    guidance: "Their triangular bodies and pointed rostrums make them look like animated arrows or underwater spiders.",
    returnLine: "I drew the legs extra long so everyone will recognize one.",
  },
  {
    id: "red-schoolhouse-rosie",
    name: "Rosie",
    title: "Age 6 · Student",
    sceneId: "elverson-red-schoolhouse",
    at: { x: 8.2, y: 5.5 },
    intro: "I love all Sea Creatures! Did you know Crevalle jacks are powerful schooling fishes with broad chests and deeply forked tails?",
    guidance: "They can handle an unusual range of water, from the open sea into salty rivers.",
    returnLine: "There are so many sea creatures to love and learn about!",
  },
  {
    id: "red-schoolhouse-juliana",
    name: "Juliana",
    title: "Age 6 · Student",
    sceneId: "elverson-red-schoolhouse",
    at: { x: 10.5, y: 4.5 },
    intro: "Goliath Groupers are enormous, thick-bodied fish that rest around reefs, wrecks, and ledges.",
    guidance: "A sudden opening of the mouth creates suction strong enough to sweep prey inside.",
    returnLine: "Their size makes them impressive, but their habitat still needs protection.",
  },
  {
    id: "programmer-harlan",
    name: "Programmer Harlan",
    title: "Marine Robotics Programmer",
    sceneId: "elverson-marine-research-lab",
    at: { x: 3.5, y: 4.5 },
    intro: "I'm working on an underwater robot that can collect coral samples so we can understand what makes certain species vulnerable or resilient to changing ocean conditions.",
    guidance: "Many corals are susceptible to high temperatures, storm surge, and even disease.",
    returnLine: "Careful sampling lets us study those stresses without causing needless damage.",
  },
  {
    id: "marine-biologist-jonah",
    name: "Marine Biologist Jonah",
    title: "Marine Biologist",
    sceneId: "aquarium-deep-gallery",
    at: { x: 4.5, y: 6.25 },
    patrol: {
      mode: "ping-pong",
      speed: 0.5,
      pauseMs: 900,
      playerPauseDistance: 1,
      waypoints: [{ x: 4.5, y: 6.25 }, { x: 13.5, y: 6.25 }],
    },
    intro: "Did you know that last year we discovered over a thousand new sea creatures? Who knows what else might be hiding in the deep…",
    guidance: "New discoveries begin with careful observation, good records, and questions no one has answered yet.",
    returnLine: "The next unknown species could be waiting beyond any familiar reef.",
  },
  {
    id: "explorer-jordan",
    name: "Explorer Jordan",
    title: "Age 10 · Explorer",
    sceneId: "aquarium-deep-gallery",
    at: { x: 19, y: 6.25 },
    patrol: {
      mode: "ping-pong",
      speed: 0.62,
      pauseMs: 600,
      playerPauseDistance: 1,
      waypoints: [{ x: 19, y: 6.25 }, { x: 28.5, y: 6.25 }],
    },
    intro: "I am soooo excited to collect all the creatures for Mr. Easterling! The first thing I am going to do is find a boat so I can explore every region.",
    guidance: "A boat opens new waters, but every trip still needs an adult-approved plan, safety gear, and respect for wildlife.",
    returnLine: "Pelora City has to be connected to some incredible places!",
  },
  {
    id: "henry",
    name: "Henry",
    title: "Age 8 · Disruption Player",
    age: 8,
    sceneId: "coral-home",
    at: { x: 4, y: 4 },
    intro: "My deck is Disruption. I like finding clever ways to interrupt a plan without losing track of my own ecosystem.",
    guidance: "Timing matters: a disruptive card is strongest when it solves the problem in front of you.",
    returnLine: "My Disruption deck is ready for another match whenever you are.",
    duel: {
      encounterId: "encounter-elverson-reef-henry",
      deckId: "disruption",
      victoryTarget: 10,
      difficulty: "hard",
      crest: "Disruption Star",
      challengeLine: "Want to see whether you can keep your plan together in a 10 VP duel?",
      rematchLine: "Ready for another 10 VP duel? I'll keep looking for the perfect moment to interrupt your plan.",
      victoryLine: "Nice recovery! You kept your ecosystem working even when I changed the timing.",
    },
  },
  {
    id: "reef-house-charlie",
    name: "Charlie",
    title: "Age 10 · Stinging Fortress Player",
    age: 10,
    sceneId: "coral-home",
    at: { x: 6, y: 4 },
    intro: "I play Stinging Fortress. Anemones and defensive reef creatures make my ecosystem hard to push around.",
    guidance: "Defense works best when the creatures protecting one another still advance your plan.",
    returnLine: "Stinging Fortress is ready for another challenger.",
    duel: {
      encounterId: "encounter-elverson-reef-charlie",
      deckId: "stinging-fortress",
      victoryTarget: 10,
      difficulty: "hard",
      crest: "Stinging Star",
      challengeLine: "Can your ecosystem find a path through my defenses in a 10 VP duel?",
      rematchLine: "Let's play another 10 VP duel. This time I'll make my fortress even tougher to crack.",
      victoryLine: "You found the opening without rushing. That's exactly how to play around a strong defense.",
    },
  },
  {
    id: "reef-house-danny",
    name: "Danny",
    title: "Age 12 · Blue Water Player",
    age: 12,
    skinTone: "Black",
    sceneId: "coral-home",
    at: { x: 4, y: 5.4 },
    intro: "My Blue Water deck follows fast-moving life across open water.",
    guidance: "A broad habitat can create room for schools, hunters, and support cards to work together.",
    returnLine: "Blue Water is ready to race across the table again.",
    duel: {
      encounterId: "encounter-elverson-reef-danny",
      deckId: "blue-water",
      victoryTarget: 10,
      difficulty: "hard",
      crest: "Blue Water Star",
      challengeLine: "Want to test your ecosystem against mine in a fast 10 VP duel?",
      rematchLine: "Ready for another 10 VP race? My Blue Water deck won't slow down.",
      victoryLine: "Great game! You kept up with the open water and built the stronger ecosystem.",
    },
  },
  {
    id: "jack",
    name: "Jack",
    title: "Murky Water Player",
    sceneId: "coral-home",
    at: { x: 6, y: 5.4 },
    intro: "I play Murky Water. Estuaries can change quickly, so I built my deck to adapt.",
    guidance: "Flexible creatures and useful support cards help when conditions shift.",
    returnLine: "Murky Water always has another route through the estuary, so I'm ready for a rematch.",
    duel: {
      encounterId: "encounter-elverson-reef-jack",
      deckId: "murky-water",
      victoryTarget: 10,
      difficulty: "hard",
      crest: "Murky Water Star",
      challengeLine: "Can your deck adapt when the water changes? Let's find out in a 10 VP duel.",
      rematchLine: "Let's try another 10 VP duel. Murky Water has more than one way to win.",
      victoryLine: "You adapted faster than I did. That's the best way through changing conditions.",
    },
  },
  {
    id: "landon",
    name: "Landon",
    title: "Age 10 · The Abyss Player",
    age: 10,
    sceneId: "deep-home",
    at: { x: 4, y: 4.5 },
    intro: "I'm designing The Abyss around the strange creatures and extreme conditions of the deep sea.",
    guidance: "A deep-ocean deck needs a plan for building toward creatures that take time and resources to support.",
    returnLine: "The Abyss is ready for another dive.",
    duel: {
      encounterId: "encounter-elverson-deep-landon",
      deckId: "the-abyss",
      victoryTarget: 10,
      difficulty: "hard",
      crest: "Abyss Star",
      challengeLine: "Ready to see what rises from The Abyss in a 10 VP duel?",
      rematchLine: "Let's descend again. The Abyss has a different surprise for this 10 VP rematch.",
      victoryLine: "You built your ecosystem before my biggest creatures could take over. Well played!",
    },
  },
  {
    id: "oliver",
    name: "Oliver",
    title: "Age 11 · Deep Waters Player",
    age: 11,
    sceneId: "deep-home",
    at: { x: 6, y: 4.5 },
    intro: "My deck is Deep Waters. I want every card to feel like another step away from the sunlight.",
    guidance: "Even the deepest ecosystem depends on energy and relationships that connect its creatures.",
    returnLine: "Deep Waters is ready for another expedition.",
    duel: {
      encounterId: "encounter-elverson-deep-oliver",
      deckId: "deep-waters",
      victoryTarget: 10,
      difficulty: "hard",
      crest: "Deep Waters Star",
      challengeLine: "Want to follow my ecosystem into Deep Waters for a 10 VP duel?",
      rematchLine: "Ready for another 10 VP expedition into Deep Waters?",
      victoryLine: "You kept every layer of your ecosystem connected, even this far below the sunlight.",
    },
  },
  {
    id: "charlotte",
    name: "Charlotte",
    title: "Age 13 · Open Ocean Player",
    age: 13,
    sceneId: "elverson-oceanic-home",
    at: { x: 5, y: 2 },
    intro: "I play Open Ocean, where speed, distance, and schooling creatures shape every turn.",
    guidance: "Open water may look empty, but its food web stretches from plankton to the largest hunters.",
    returnLine: "My Open Ocean deck is ready for another voyage.",
    duel: {
      encounterId: "encounter-elverson-oceanic-charlotte",
      deckId: "open-ocean-hunt",
      victoryTarget: 30,
      difficulty: "hard",
      crest: "Open Ocean Star",
      challengeLine: "Want to race across the Open Ocean in a full 30 VP duel?",
      rematchLine: "Let's launch another 30 VP Open Ocean duel. Keep an eye on my schools this time.",
      victoryLine: "You read the whole food web instead of chasing one fast creature. Great match!",
    },
  },
  {
    id: "eloise",
    name: "Eloise",
    title: "Age 7 · Pelagic Zone Player",
    age: 7,
    sceneId: "elverson-oceanic-home",
    at: { x: 4, y: 4.5 },
    intro: "My deck is Pelagic Zone. Pelagic means the open part of the water, away from the shore and sea floor.",
    guidance: "Creatures there may travel enormous distances to find food or safe conditions.",
    returnLine: "My Pelagic Zone is ready to travel again.",
    duel: {
      encounterId: "encounter-elverson-oceanic-eloise",
      deckId: "pelagic-zone",
      victoryTarget: 10,
      difficulty: "hard",
      crest: "Pelagic Star",
      challengeLine: "Would you like a friendly 10 VP duel with my Pelagic Zone deck?",
      rematchLine: "Can we play another 10 VP duel? My Pelagic Zone creatures are ready to travel.",
      victoryLine: "That was fun! You found the best path across the open water.",
    },
  },
  {
    id: "edith",
    name: "Edith",
    title: "Age 7 · Plankton Bloom Player",
    sceneId: "elverson-oceanic-home",
    at: { x: 6, y: 4.5 },
    intro: "I play Plankton Bloom! Tiny drifting life can feed an enormous ocean community.",
    guidance: "A bloom can support a food web, but too much growth can also signal that an ecosystem is out of balance.",
    returnLine: "Plankton Bloom is still being tuned for a future match.",
  },
  {
    id: "william",
    name: "William",
    title: "Murky Water's Revenge Player",
    sceneId: "elverson-hybrid-home",
    at: { x: 4, y: 4 },
    intro: "I play Murky Water's Revenge, with a heavy focus on apex sharks.",
    guidance: "Big predators need a strong food web beneath them, even in an aggressive deck.",
    returnLine: "Finn and I are still tuning Murky Water's Revenge for a future match.",
  },
  {
    id: "hybrid-house-olivia",
    name: "Olivia",
    title: "Whirlpool Player",
    sceneId: "elverson-hybrid-home",
    at: { x: 6, y: 4 },
    intro: "Whirlpool mixes Disruption and Blue Water so I can redirect a match while my ocean keeps moving.",
    guidance: "Hybrid decks work when their two plans share cards and resources instead of competing for space.",
    returnLine: "Whirlpool is still being tuned for a future match.",
  },
  {
    id: "hybrid-house-alyssa",
    name: "Alyssa",
    title: "Coral Ledge Player",
    sceneId: "elverson-hybrid-home",
    at: { x: 4, y: 5.4 },
    intro: "Coral Ledge is my Reef and Deep hybrid. The ledge connects bright coral growth to darker water below.",
    guidance: "The best hybrid cards help both habitats contribute to one shared ecosystem plan.",
    returnLine: "Coral Ledge is still being tuned for a future match.",
  },
  {
    id: "hybrid-house-henry",
    name: "Henry",
    title: "Drop Off Player",
    sceneId: "elverson-hybrid-home",
    at: { x: 6, y: 5.4 },
    intro: "My Drop Off deck combines Reef and Open Ocean creatures along a steep habitat boundary.",
    guidance: "A hybrid deck needs cards that make the transition between its habitats worthwhile.",
    returnLine: "Drop Off is still being tuned for a future match.",
  },
]);
